apiVersion: v1
kind: Service
metadata:
        name: internalloadbalancer
spec:
     selector:
             name: mysql
     type: ClusterIP
     ports:
     - targetPort: 3306
       port: 8080
            
